# Generated by Django 3.1.5 on 2021-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('year_of_experience', models.IntegerField()),
                ('departmnet_Id', models.CharField(choices=[('HR', 'Hr'), ('IT', 'It'), ('Finance', 'Finance')], default='IT', max_length=10)),
                ('resume_url', models.URLField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
