# Generated by Django 3.1.5 on 2021-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20210128_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(default=''),
        ),
    ]
