# Generated by Django 3.1.5 on 2021-01-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20210128_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_admin',
        ),
    ]
