# Generated by Django 3.1.5 on 2021-01-29 12:16

import candidate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20210129_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to=' ', validators=[candidate.validators.validate_file_extension]),
        ),
    ]
