# Generated by Django 3.1.5 on 2021-01-29 12:26

import candidate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20210129_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to='http://documents/', validators=[candidate.validators.validate_file_extension]),
        ),
    ]
